target_column:
- Strength

numerical_column:
- AgeInDays
- BlastFurnaceSlag
- CementComponent
- SuperplasticizerComponent
- WaterComponent

drop_columns:    #### 
- FineAggregateComponent
- CoarseAggregateComponent
- FlyAshComponent

target_column:
- Strength